### ISSUE TITLE
Consider Using ast.literal_eval for Safer Evaluation

### ISSUE THREAD

**Issue by kevinastone** [peterdemin/SublimePPrint#1]
Not too excited to be have arbitrary python code evaluated when you pretty print.  Consider using [ast.literal_eval](https://docs.python.org/2/library/ast.html#ast.literal_eval) instead of plain `eval`.

**Comment by peterdemin** [comment]
It is vital for me to be able to parse collections.OrderedDict. AFAIK it is impossible using ast.literal_eval
